### ISSUE TITLE
Feature request: trace parent for post-document-load resource fetch spans

### ISSUE THREAD

**Issue by sfishel-splunk** [signalfx/splunk-otel-js-web#357]
The document-load plugin supports [defining a trace parent for resource fetch spans](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/web/opentelemetry-instrumentation-document-load#optional-send-a-trace-parent-from-your-server), but there is no way to do the same for resource fetches that happen after the document load. 

Proposal: support defining the trace parent with a `data-traceparent` attribute on the `<script>` element that loads the resource, i.e.

```
  <script src="my-script.js" data-traceparent="00-ab42124a3c573678d4d8b21ba52df3bf-d21f7bc17caa5aba-01"></script>
```

If this approach seems reasonable, I'd be happy to submit a PR.

**Comment by t2t2** [comment]
First off for all splunk distributions of otel `Server-Timing: traceparent;desc=00-...` header [has been agreed upon as the way to do this](https://github.com/signalfx/gdi-specification/blob/main/specification/configuration.md#instrumentation-libraries). This is because [it's the only way a header can be read by browser](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceResourceTiming/serverTiming) for scripts/stylesheets/images/other background requests like favicons (nuxt example app shows it working with apm linking in splunk observability ui as there all files are served by nodejs server w/ splunk-otel-js). All of the server distributions write it, all of the rums (including android & ios) read it.

---

Now let's ignore that part and evaluate this suggested approach - I think you'd have quite a few implementation headaches

The reason document-load plugin can do that for the html document is because the document is generated by the span it includes info for - just take the current span while rendering the page and include trace & span ids.

For script tags this cannot be included in the page rendering since you'd need to predict what the trace and span id for js request would be - quite impossible without a time machine or telling these in the request (in which case server telling the client id's wouldn't be needed at all, tho I can do a whole separate thing on why I think otel propagators are a mistake when it comes to client -> server propagation, [thanks googlebot](https://www.tomanthony.co.uk/blog/googlebot-javascript-random/))

For post-loading you'd need to put the info on the script tag during execution of the script. [Sure, can be done](https://developer.mozilla.org/en-US/docs/Web/API/Document/currentScript) up until you decide to have multiple bundles to separate IE from modern browsers via module/nomodule pattern. Then you'd also need awareness of what url is used to load the script

But then you'd have issue of what do you set it to. Can't read header, otherwise instrumentation wouldn't need to find other ways to do this. Pretty much the only way would be for serving server to modify each response adding a snippet setting the value to the tag. Not really something I'd imagine doing when serving files off a CDN.

Then finally on instrumentation side, currently only [ResourceTiming](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceResourceTiming) objects are used to generate the spans without linking it to the loading `<script>` tag. Though imo it would be a good addition to rewrite the instrumentation based on MutationObserver to detect the script (and other) tags and performance API to populate the actual network time to allow causality of click -> script load. Anyways additional implementation gotcha
